name: Regenerate MATLAB bindings
# This action regenerates the MATLAB bindings, for more details
# see doc/dev/faqs.md#how-to-add-wrap-a-new-class-or-function-with-swig 

on:
  workflow_dispatch:
  pull_request:

jobs:
    regenerate-matlab-bindings:
        name: "Regenerate MATLAB bindings"
        runs-on: [ubuntu-20.04]
        steps:
        - uses: actions/checkout@v2

        - name: Install SWIG for that supports MATLAB
          run: |
            sudo apt-get remove swig swig4.0
            cd ..
            git clone https://github.com/robotology-dependencies/swig/
            cd swig
            git checkout matlab
            sh autogen.sh
            ./configure --with-matlab
            make 
            sudo make install

        - name: Verify which SWIG is found 
          run: |
            which swig
            swig --help

        - name: Configure and compile YARP
          run: |
            # Install YARP dependencies
            sudo sh -c 'echo "deb http://www.icub.org/ubuntu focal contrib/science" > /etc/apt/sources.list.d/icub.list'
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 57A5ACB6110576A6
            sudo apt-get update
            sudo apt-get install build-essential git cmake cmake-curses-gui \
            ycm-cmake-modules libeigen3-dev libace-dev libedit-dev libsqlite3-dev \
            libtinyxml-dev qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev \
            qml-module-qtquick2 qml-module-qtquick-window2 \
            qml-module-qtmultimedia qml-module-qtquick-dialogs \
            qml-module-qtquick-controls qml-module-qt-labs-folderlistmodel \
            qml-module-qt-labs-settings libqcustomplot-dev libgraphviz-dev \
            libjpeg-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-libav liboctave-dev
            # Clone YARP
            # GITHUB_BASE_REF is defined on Pull Requests
            if [[ -z "${GITHUB_BASE_REF}" ]]; then
                YARP_BRANCH="${GITHUB_REF}"
            else
                YARP_BRANCH="${GITHUB_BASE_REF}"
            fi
            git clone https://github.com/robotology/yarp -b ${YARP_BRANCH}
            # Configure, build and install YARP and regenerate yarp-matlab-bindings
            cd yarp
            mkdir build
            cd build
            cmake -DYARP_COMPILE_EXECUTABLES:BOOL=OFF ..
            make
            sudo make install
            # Configure yarp-matlab-bindings
            cd ../..
            # Remove autogenerate files to ensure that removed files are actually removed
            git rm -r matlab/autogenerated
            mkdir -p build
            cd build
            cmake -DYARP_SOURCE_DIR:PATH=${GITHUB_WORKSPACE}/yarp -DYARP_USES_OCTAVE:BOOL=ON -DYARP_GENERATE_MATLAB:BOOL=ON ..
            cat CMakeCache.txt
            make
            cd ..
            # After bindings are generated, we modify the names of generic files to avoid conflicts with CasADi
            ./fix_generic_names_in_autogenerated_files.sh

        - name: Check local changes due to bindings generation
          run: |
            git status
            

        - name: Create Pull Request
          id: cpr
          uses: peter-evans/create-pull-request@v3
          with:
            commit-message: 'update matlab bindings'
            committer: GitHub <noreply@github.com>
            branch: regenerate-matlab-bindings
            delete-branch: true
            title: 'update matlab bindings'
            body: |
              This is a PR that regenerated the MATLAB/Octave YARP bindings.
                            
              For more info, check the [documentation on MATLAB bindings](https://github.com/robotology/yarp-matlab-bindings). 

        - name: Check outputs
          run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

